name: cloud-gallery
services:
  mysql:
    image: mysql:8.0
    container_name: painting_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: paint
      MYSQL_USER: painter
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - painting_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:8.0
    container_name: painting_redis
    restart: always
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - painting_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  gallery_backend:
    build: ./云上画廊-back/
    container_name: gallery_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: paint
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: 123456
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - painting_network
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:
networks:
  painting_network:
    driver: bridge
    
